TravelNM/Controllers/AdminController.cs
using InterfacesTravelMN;
using Model;
using System.Linq;
using System.Web.Mvc;
using TravelNM.Models;


namespace TravelNM.Controllers
{
    public class AdminController : BaseController
    {
        private IMaintenance<City> _maintenanceCity;
        private IMaintenance<TravelPackage> _maintenanceTravelPackage;
        private IMaintenance<TravelPackageBuy> _maintenanceTravelPackageBuy;
        private IMaintenance<Customer> _maintenanceCustomer;

        public AdminController(IMaintenance<City> maintenanceCity, IMaintenance<TravelPackage> maintenanceTravelPackage,
            IMaintenance<TravelPackageBuy> maintenanceTravelPackageBuy, IMaintenance<Customer> maintenanceCustomer)
        {
            this._maintenanceCity = maintenanceCity;
            this._maintenanceTravelPackage = maintenanceTravelPackage;
            this._maintenanceTravelPackageBuy = maintenanceTravelPackageBuy;
            this._maintenanceCustomer = maintenanceCustomer;
        }

        public ActionResult Index(DashboardView dashboardview)
        {
            dashboardview.TotalCities = _maintenanceCity.GetAll().Count();
            dashboardview.TotalPackages = _maintenanceTravelPackage.GetAll().Count();
            dashboardview.TotaSoldPackages = _maintenanceTravelPackageBuy.GetAll().Count();
            dashboardview.TotalCustomers = _maintenanceCustomer.GetAll().Where(c => c.Status == 1).Count();

            dashboardview.TotaSoldPackagesCanceled = _maintenanceTravelPackageBuy.GetAll().Where(s => s.Status == 3).Count();
            dashboardview.TotaSoldPackagesWaitingPayment= _maintenanceTravelPackageBuy.GetAll().Where(s => s.Status == 1).Count();
            dashboardview.TotaSoldPackagesPaid = _maintenanceTravelPackageBuy.GetAll().Where(s => s.Status == 2).Count();

            return View(dashboardview);
        }

    }
}

TravelNM/Controllers/AuthenticationController.cs
using InterfacesTravelMN;
using Model;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using TravelNM.Helpers;
using TravelNM.Models;

namespace TravelNM.Controllers
{
    [AllowAnonymous]
    public class AuthenticationController : BaseController
    {
        private IAuthentication _authentication;
        private IMaintenance<Customer> _maintenance;
        private IMaintenance<City> _maintenanceCity;

        public AuthenticationController(IAuthentication authentication, IMaintenance<Customer> maintenance, 
            IMaintenance<City> maintenanceCity)
        {
            this._authentication = authentication;
            this._maintenance = maintenance;
            this._maintenanceCity = maintenanceCity;
        }

        public ActionResult LoginAdmin(CustomerView customerview)
        {
            New(customerview);
            ViewBag.Action = "LoginAdmin";
            return View("Login");
        }
        public ActionResult LoginCustomer(string ReturnUrl, CustomerView customerview)
        {
            New(customerview);
            Session["ReturnUrl"] = ReturnUrl;
            ViewBag.Action = "LoginCustomer";
            return View("Login");
        }

        public ActionResult New(CustomerView customerview)
        {
            customerview.Cities = _maintenanceCity.GetAll();
            return View(customerview);
        }

        [HttpPost]
        public ActionResult LoginCustomer(Customer customer, Methods methods)
        {
            try
            {
                customer.Password = methods.GenHashSalt(customer.Password, _maintenance.Search(new[] { customer.Email }).ToList().First().Salt);

                if (this._authentication.LoginCustomer(customer) == null)
                    return RedirectToAction("Index", "UnauthorizedError");
                else
                {
                    FormsAuthentication.SetAuthCookie(customer.Email, false);
                    Session["IdCustomer"] = _maintenance.Search(new[] { customer.Email }).ToList().First().Id.ToString();

                    string ReturnUrl = (string)Session["ReturnUrl"];
                    if (string.IsNullOrWhiteSpace(ReturnUrl))
                        return RedirectToAction("BuyPackageIndex", "TravelPackage");
                    else
                        return Redirect(ReturnUrl);
                }
            }
            catch
            {
                return RedirectToAction("Index", "UnauthorizedError");
            }
        }

        [HttpPost]
        public ActionResult LoginAdmin(User user)
        {
            try
            {
                if (this._authentication.Login(user) == null)
                    return RedirectToAction("Index", "UnauthorizedError");
                else
                {
                    FormsAuthentication.SetAuthCookie(user.Email, false);
                    return RedirectToAction("Index", "Admin");
                }
            }
            catch
            {
                return RedirectToAction("Index", "UnauthorizedError");
            }
        }

        public ActionResult SetCulture(string culture)
        {
            // Validate input
            culture = CultureHelper.GetImplementedCulture(culture);
            RouteData.Values["culture"] = culture;  // set culture

            var controller = (Request.UrlReferrer.Segments.Skip(2).Take(1).SingleOrDefault() ?? "Home").Trim('/');
            // Home is default controller

            var action = (Request.UrlReferrer.Segments.Skip(3).Take(1).SingleOrDefault() ?? "Index").Trim('/');

            var id = (Request.UrlReferrer.Segments.Skip(4).Take(1).SingleOrDefault() ?? "0").Trim('/');

            if ("0" == id)
                return RedirectToAction(action, controller, new { culture = culture });
            else
                return RedirectToAction(action, controller, new { culture = culture, id = id });

        }

        public void Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            FormsAuthentication.RedirectToLoginPage();
        }
    }
}

TravelNM/Controllers/CustomerController.cs
using InterfacesTravelMN;
using Model;
using System;
using System.Linq;
using System.Web.Mvc;
using TravelNM.Models;
using System.Web.Helpers;
using System.Web.Security;

namespace TravelNM.Controllers
{
    public class CustomerController : BaseController
    {
        private IMaintenance<Customer> _maintenance;
        private IMaintenance<City> _maintenanceCity;

        public CustomerController(IMaintenance<Customer> maintenance, IMaintenance<City> maintenanceCity)
        {
            this._maintenance = maintenance;
            this._maintenanceCity = maintenanceCity;
        }

        public ActionResult Index()
        {
            return View(this._maintenance.GetAll());
        }

        public ActionResult New(CustomerView customerview)
        {
            customerview.Cities = _maintenanceCity.GetAll();
            return View(customerview);
        }

        public ActionResult Edit(int id, CustomerView customerview)
        {
            customerview.Customer = this._maintenance.Get(id);
            customerview.Cities = _maintenanceCity.GetAll();
            customerview.Customer.SupportPassword = customerview.Customer.Password;
            return View(customerview);
        }

        public ActionResult EditCustomer(int id, CustomerView customerview)
        {
            if (id == int.Parse(Session["idCustomer"].ToString()))
            {
                customerview.Customer = this._maintenance.Get(id);
                customerview.Cities = _maintenanceCity.GetAll();
                customerview.Customer.SupportPassword = customerview.Customer.Password;
                return View(customerview);
            }
            else
                return RedirectToAction("EditCustomer/" + (Session["idCustomer"]).ToString());
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Update(CustomerView customerview, Methods methods)
        {
            var culture = System.Globalization.CultureInfo.CurrentCulture;
   
            if (customerview.Customer.Password.ToString().Trim().Length < 6)
            {
                if (culture.Name == "en-US")
                    MessageVal("The password field duty of 6 or more characters.", "Edit" + Convert.ToString(customerview.Customer.Id));
                else
                    MessageVal("O campo de senha dever de 6 ou mais caracteres.", "Edit" + Convert.ToString(customerview.Customer.Id));

                return null;
            }
            else
            {
                if (Session["idCustomer"] == null)
                    customerview.Customer.Status = int.Parse(Request.Form["Status"].ToString());

                if (customerview.Customer.Password != customerview.Customer.SupportPassword)
                    customerview.Customer.Password = methods.GenHashSalt(customerview.Customer.Password, customerview.Customer.Salt);

                this._maintenance.Update(customerview.Customer);

                if (Session["idCustomer"] == null)
                    return RedirectToAction("Index");
                else
                    return RedirectToAction("EditCustomer/" + (Session["idCustomer"]).ToString());
            }      
        }

        [HttpPost]
        public JsonResult Delete(Customer customer)
        {
            this._maintenance.Delete(customer);
            return Json("ok");
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        [AllowAnonymous]
        public ActionResult Create(CustomerView customerview, Methods methods)
        {
            var culture = System.Globalization.CultureInfo.CurrentCulture;

            if (ExistsEmail(customerview.Customer.Email))
            {
                if (culture.Name == "en-US")
                    MessageVal("The email is already registered in our database.", "New");
                else
                    MessageVal("E-mail já resgistrado em nossa base de dados.", "New");

                return null;
            }
            else
                if (customerview.Customer.Password.ToString().Trim().Length < 6)
                {
                    if (culture.Name == "en-US")
                        MessageVal("The password field duty of 6 or more characters.", "New");
                    else
                        MessageVal("O campo de senha dever de 6 ou mais caracteres.", "New");

                    return null;
                }
                else
                {
                    customerview.Customer.Salt = Crypto.GenerateSalt();
                    customerview.Customer.Password = methods.GenHashSalt(customerview.Customer.Password, customerview.Customer.Salt);

                    if (Request.Form["Status"] != null)
                        customerview.Customer.Status = int.Parse(Request.Form["Status"].ToString());
                    else
                        customerview.Customer.Status = 1;

                    this._maintenance.Save(customerview.Customer);
                    return RedirectToAction("Index");
                }
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        [AllowAnonymous]
        public ActionResult CreateUser(CustomerView customerview, Methods methods)
        {
            var culture = System.Globalization.CultureInfo.CurrentCulture;
            
            customerview.Customer.Salt = Crypto.GenerateSalt();
            customerview.Customer.Password = methods.GenHashSalt(customerview.Customer.Password, customerview.Customer.Salt);

            if (Request.Form["Status"] != null)
                customerview.Customer.Status = int.Parse(Request.Form["Status"].ToString());
            else
                customerview.Customer.Status = 1;

            this._maintenance.Save(customerview.Customer);

            FormsAuthentication.SetAuthCookie(customerview.Customer.Email, false);
            Session["IdCustomer"] = _maintenance.Search(new[] { customerview.Customer.Email }).ToList().First().Id.ToString();

            string ReturnUrl = (string)Session["ReturnUrl"];
            if (string.IsNullOrWhiteSpace(ReturnUrl))
                return RedirectToAction("BuyPackageIndex", "TravelPackage");
            else
                return Redirect(ReturnUrl);
        }

        public void MessageVal(string Message, string Url)
        {
            Response.Write("<script> alert('" + Message + "'); window.location = '" + Url + "' </script>");
        }

        public Boolean ExistsEmail(string Email)
        {
            var Customers = _maintenance.GetAll();

            foreach (var customer in Customers)
            {
                if (customer.Email == Email)
                    return true;
            }
            return false;
        }
    }
}

TravelNM/Controllers/UserController.cs
using InterfacesTravelMN;
using Model;
using System.Web.Mvc;

namespace TravelNM.Controllers
{
    public class UserController : BaseController
    {
        private IMaintenance<User> _maintenanceUser;

        public UserController(IMaintenance<User> maintenanceUser)
        {
            this._maintenanceUser = maintenanceUser;
        }

        public ActionResult Index()
        {
            return View(this._maintenanceUser.GetAll());
        }

        public ActionResult New()
        {
            return View(new User());
        }

        public ActionResult Edit(int id)
        {
            return View(this._maintenanceUser.Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Update(User user)
        {
            this._maintenanceUser.Update(user);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult Delete(User user)
        {
            this._maintenanceUser.Delete(user);
            return Json("ok");
        }


        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(User user)
        {
            this._maintenanceUser.Save(user);
            return RedirectToAction("Index");
        }
    }
}

TravelNM/Views/Shared/_LayoutAdmin.cshtml
@{
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
}

@helper selected(string c, string culture)
{
    if (c == culture)
    {
        <i class="fa fa-location-arrow"></i>
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/assets/plugins/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="~/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/assets/plugins/pace/pace-theme-big-counter.css" rel="stylesheet" />
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link href="~/assets/css/main-style.css" rel="stylesheet" />
    @RenderSection("css", required: false)
</head>
<body>
    <!--  wrapper -->
    <div id="wrapper">
        <!-- navbar top -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar">
            <!-- navbar-header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Admin")">
                    <h2 style="color:#ffffff">TRAVEL MN</h2>
                </a>
            </div>
            <!-- end navbar-header -->
            <!-- navbar-top-links -->
            <ul class="nav navbar-top-links navbar-right">
                <!-- main dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-location-arrow fa-3x"></i>
                    </a>
                    <!-- dropdown tasks -->
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="@Url.Action("SetCulture", "Authentication", new { culture = "pt-br" })">
                                Português @selected("pt-br", culture)
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("SetCulture", "Authentication", new { culture = "en-us" })">
                                English @selected("en-us", culture)
                            </a>
                        </li>
                    </ul>
                    <!-- end dropdown-tasks -->
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-3x"></i>
                    </a>
                    <!-- dropdown user-->
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i>@Resources.User.UserProfile</a>
                        </li>
                        @*<li>
                        <a href="#"><i class="fa fa-gear fa-fw"></i>Settings</a>
                    </li>*@
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("Logout", "Authentication")"><i class="fa fa-sign-out fa-fw"></i>@Resources.User.Logout</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "City")"><i class="fa fa-list fa-fw"></i> @Resources.City.Cities</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "TravelPackage")"><i class="fa fa-files-o fa-fw"></i> @Resources.TravelPackage.Packages</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "User")"><i class="fa fa-lock fa-fw"></i> @Resources.User.Users</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Customer")"><i class="fa fa-users fa-fw"></i> @Resources.Customer.Customers</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "TravelPackageBuy")"><i class="fa fa-shopping-cart fa-fw"></i> @Resources.SoldPackage.SoldPackages</a>
                        </li>

                        <li>
                            <a href="@Url.Action("Index", "QueryProcessor")"><i class="fa fa-question"></i> @Resources.QueryProcessor.QueriesProcessor</a>
                        </li>
            </ul>
                    <!-- end dropdown-user -->
                </li>
                <!-- end main dropdown -->
            </ul>
            <!-- end navbar-top-links -->
        </nav>
        <!-- end navbar top -->
        <!-- navbar side -->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <!-- sidebar-collapse -->
            <div class="sidebar-collapse">
                <!-- side-menu -->
                <ul class="nav" id="side-menu">
                    <li>
                        <!-- user image section-->
                        <div class="user-section">
                        </div>
                        <!--end user image section-->
                    </li>
                    <li class="">
                        <a href="@Url.Action("Index", "Admin")"><i class="fa fa-dashboard fa-fw"></i> @Resources.Global.Dashboard</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "City")"><i class="fa fa-list fa-fw"></i> @Resources.City.Cities</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "TravelPackage")"><i class="fa fa-files-o fa-fw"></i> @Resources.TravelPackage.Packages</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "User")"><i class="fa fa-lock fa-fw"></i> @Resources.User.Users</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Customer")"><i class="fa fa-users fa-fw"></i> @Resources.Customer.Customers</a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "QueryProcessor")"><i class="fa fa-question"></i> @Resources.QueryProcessor.QueriesProcessor</a>
                    </li>
                </ul>
                <!-- end side-menu -->
            </div>
            <!-- end sidebar-collapse -->
        </nav>
        <!-- end navbar side -->
        <!--  page-wrapper -->
        @RenderBody()
        <!-- end page-wrapper -->
    </div>
    <!-- end wrapper -->
    <!-- Core Scripts - Include with every page -->
    <script src="~/assets/plugins/jquery-1.10.2.js"></script>
    <script src="~/assets/plugins/bootstrap/bootstrap.min.js"></script>
    <script src="~/assets/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/assets/plugins/pace/pace.js"></script>
    <script src="~/assets/scripts/siminta.js"></script>

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

TravelNM/Views/Shared/_LayoutAdminCustomer.cshtml
@{
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
}

@helper selected(string c, string culture)
{
    if (c == culture)
    {
        <i class="fa fa-location-arrow"></i>
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/assets/plugins/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="~/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/assets/plugins/pace/pace-theme-big-counter.css" rel="stylesheet" />
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link href="~/assets/css/main-style.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("css", required: false)
</head>
<body>
    <!--  wrapper -->
    <div id="wrapper">
        <!-- navbar top -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar">
            <!-- navbar-header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("BuyPackageIndex", "TravelPackage")">
                    <h2 style="color:#ffffff">TRAVEL MN</h2>
                </a>
            </div>
            <!-- end navbar-header -->
            <!-- navbar-top-links -->
            <ul class="nav navbar-top-links navbar-right">
                <!-- main dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-location-arrow fa-3x"></i>
                    </a>
                    <!-- dropdown tasks -->
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="@Url.Action("SetCulture", "Authentication", new { culture = "pt-br" })">
                                Português @selected("pt-br", culture)
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("SetCulture", "Authentication", new { culture = "en-us" })">
                                English @selected("en-us", culture)
                            </a>
                        </li>
                    </ul>
                    <!-- end dropdown-tasks -->
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-3x"></i>
                    </a>
                    <!-- dropdown user-->
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="@Url.Action("EditCustomer", "Customer", new { id = Session["idCustomer"]})"><i class="fa fa-user fa-fw"></i> @Resources.Customer.Profile</a>
                        </li>
                        @*<li>
                                <a href="#"><i class="fa fa-gear fa-fw"></i>Settings</a>
                            </li>*@
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("Logout", "Authentication")"><i class="fa fa-sign-out fa-fw"></i>@Resources.User.Logout</a>
                        </li>
                        <li class="">
                            <a href="@Url.Action("MyPackage", "TravelPackageBuy")"><i class="fa fa-dashboard fa-fw"></i> @Resources.MyPackage.MyPackagesTravel</a>
                        </li>
                        <li>
                            <a href="@Url.Action("BuyPackageIndex", "TravelPackage")"><i class="fa fa-shopping-cart fa-fw"></i> @Resources.TravelPackageBuy.BuyPackages</a>
                        </li>
                    </ul>
                    <!-- end dropdown-user -->
                </li>
                <!-- end main dropdown -->
            </ul>
            <!-- end navbar-top-links -->
        </nav>
        <!-- end navbar top -->
        <!-- navbar side -->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <!-- sidebar-collapse -->
            <div class="sidebar-collapse">
                <!-- side-menu -->
                <ul class="nav" id="side-menu">
                    <li>
                        <!-- user image section-->
                        <div class="user-section">
                        </div>
                        <!--end user image section-->
                    </li>
                    <li class="">
                        <a href="@Url.Action("MyPackage", "TravelPackageBuy")"><i class="fa fa-dashboard fa-fw"></i> @Resources.MyPackage.MyPackagesTravel</a>
                    </li>
                    <li>
                        <a href="@Url.Action("EditCustomer", "Customer", new { id = Session["idCustomer"] })"><i class="fa fa-user fa-fw"></i> @Resources.Customer.Profile</a>
                    </li>
                    <li>
                        <a href="@Url.Action("BuyPackageIndex", "TravelPackage")"><i class="fa fa-shopping-cart fa-fw"></i> @Resources.TravelPackageBuy.BuyPackages</a>
                    </li>
                </ul>
                <!-- end side-menu -->
            </div>
            <!-- end sidebar-collapse -->
        </nav>
        <!-- end navbar side -->
        <!--  page-wrapper -->
        @RenderBody()
        <!-- end page-wrapper -->
    </div>
    <!-- end wrapper -->
    <!-- Core Scripts - Include with every page -->
    <script src="~/assets/plugins/jquery-1.10.2.js"></script>
    <script src="~/assets/plugins/bootstrap/bootstrap.min.js"></script>
    <script src="~/assets/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/assets/plugins/pace/pace.js"></script>
    <script src="~/assets/scripts/siminta.js"></script>

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

TravelNM/Views/Shared/_LayoutRegister.cshtml
@{
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
}

@helper selected(string c, string culture)
{
    if (c == culture)
    {
        <i class="fa fa-location-arrow"></i>
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/assets/plugins/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="~/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/assets/plugins/pace/pace-theme-big-counter.css" rel="stylesheet" />
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link href="~/assets/css/main-style.css" rel="stylesheet" />
    @RenderSection("css", required: false)
</head>
<body>
    <!--  wrapper -->
    <div id="wrapper">
        <!-- navbar top -->
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar">
            <!-- navbar-header -->
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <h2 style="color:#ffffff">TRAVEL MN</h2>
                </a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <!-- main dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-location-arrow fa-3x"></i>
                    </a>
                    <!-- dropdown tasks -->
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="@Url.Action("SetCulture", "Authentication", new { culture = "pt-br" })">
                                Português @selected("pt-br", culture)
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("SetCulture", "Authentication", new { culture = "en-us" })">
                                English @selected("en-us", culture)
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        @RenderBody()
    </div>
    <!-- end wrapper -->
    <!-- Core Scripts - Include with every page -->
    <script src="~/assets/plugins/jquery-1.10.2.js"></script>
    <script src="~/assets/plugins/bootstrap/bootstrap.min.js"></script>
    <script src="~/assets/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/assets/plugins/pace/pace.js"></script>
    <script src="~/assets/scripts/siminta.js"></script>

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>