TravelNM/Models/TravelPackageView.cs
using Model;
using System.Collections.Generic;

namespace TravelNM.Models
{
    public class TravelPackageView
    {
        public TravelPackage TravelPackage { get; set; }
        public List<City> Cities { get; set; }
    }
}

TravelNM/Controllers/TravelPackageBuyController.cs
using InterfacesTravelMN;
using Model;
using System;
using System.Web.Mvc;
using TravelNM.Models;

namespace TravelNM.Controllers
{
    public class TravelPackageBuyController : BaseController
    {
        private IMaintenance<TravelPackage> _maintenance;
        private IMaintenance<TravelPackageBuy> _maintenancebuypackage;
        private IMaintenance<Customer> _maintenancecustomer;

        public TravelPackageBuyController(IMaintenance<TravelPackage> maintenance, IMaintenance<TravelPackageBuy> maintenancebuypackage,
            IMaintenance<Customer> maintenancecustomer)
        {
            this._maintenance = maintenance;
            this._maintenancebuypackage = maintenancebuypackage;
            this._maintenancecustomer = maintenancecustomer;
        }

        public ActionResult Index()
        {
            return View(this._maintenancebuypackage.GetAll());
        }

        public ActionResult New(TravelPackageBuyView travelpackagebuyview)
        {
            travelpackagebuyview.TravelPackage = _maintenance.GetAll();
            travelpackagebuyview.Customers = _maintenancecustomer.GetAll();
            return View(travelpackagebuyview);
        }

        public ActionResult Edit(int id, TravelPackageBuyView travelpackagebuyview)
        {
            travelpackagebuyview.TravelPackageBuy = this._maintenancebuypackage.Get(id);
            travelpackagebuyview.TravelPackage = _maintenance.GetAll();
            travelpackagebuyview.Customers = _maintenancecustomer.GetAll();

            return View(travelpackagebuyview);
        }

        [HttpPost]
        public JsonResult Delete(TravelPackageBuy travelpackagebuy)
        {
            this._maintenancebuypackage.Delete(travelpackagebuy);
            return Json("ok");
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Update(TravelPackageBuyView travelpackagebuyview)
        {
            travelpackagebuyview.TravelPackageBuy.DateBuy = DateTime.Now;
            travelpackagebuyview.TravelPackageBuy.Status = int.Parse(Request.Form["Status"].ToString());

            this._maintenancebuypackage.Update(travelpackagebuyview.TravelPackageBuy);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Create(TravelPackageBuy travelpackagebuy)
        {
            travelpackagebuy.DateBuy = DateTime.Now;
            travelpackagebuy.Status = 1;
            this._maintenancebuypackage.Save(travelpackagebuy);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult CreateCustomer(TravelPackageBuy travelpackagebuy, int id)
        {
            travelpackagebuy.DateBuy = DateTime.Now;
            travelpackagebuy.Status = 1;

            travelpackagebuy.Customer = new Customer() { Id = int.Parse(Session["IdCustomer"].ToString()) };
            travelpackagebuy.TravelPackage = new TravelPackage() { Id = id };

            this._maintenancebuypackage.Save(travelpackagebuy);
            return Json("ok");
        }

        public ActionResult MyPackage()
        {
            return View(this._maintenancebuypackage.GetAllId(int.Parse(Session["IdCustomer"].ToString())));
        }

        public ActionResult DetailsMyPackage(int id)
        {
            if (_maintenancebuypackage.Get(id).Customer.Id == int.Parse(Session["idCustomer"].ToString()))
                return View(this._maintenancebuypackage.Get(id));
            else
                return RedirectToAction("MyPackage");
        }
    }
}

TravelNM/Controllers/TravelPackageController.cs
using InterfacesTravelMN;
using Model;
using System;
using System.Web.Mvc;
using TravelNM.Models;
using VDS.RDF.Query;

namespace TravelNM.Controllers
{
    public class TravelPackageController : BaseController
    {
        private IMaintenance<TravelPackage> _maintenance;

        private IMaintenance<City> _maintenanceCity;

        private RDFController _rdfcontroller;

        private IRDFMaintenance<RDFTriple> _maintenancerdf;

        public TravelPackageController(IMaintenance<TravelPackage> maintenance, IMaintenance<City> maintenanceCity,
            RDFController rdfcontroller, IRDFMaintenance<RDFTriple> maintenancerdf)
        {
            this._maintenance = maintenance;
            this._maintenanceCity = maintenanceCity;
            this._rdfcontroller = rdfcontroller;
            this._maintenancerdf = maintenancerdf;
        }

        public ActionResult Index()
        {
            return View(this._maintenance.GetAll());
        }

        public ActionResult BuyPackageIndex()
        {
            return View(this._maintenance.GetAll());
        }

        public ActionResult New(TravelPackageView travelpackageview)
        {
            travelpackageview.Cities = _maintenanceCity.GetAll();
            return View(travelpackageview);
        }

        public ActionResult Edit(int id, TravelPackageView travelpackageview)
        {
            travelpackageview.TravelPackage = this._maintenance.Get(id);
            travelpackageview.Cities = _maintenanceCity.GetAll();
            return View(travelpackageview);
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Update(TravelPackageView travelpackageview)
        {
            if (travelpackageview.TravelPackage.CityOrigin.Id != travelpackageview.TravelPackage.CityDestination.Id)
            {
                this._maintenance.Update(travelpackageview.TravelPackage);

                String Origin = _maintenanceCity.Get(travelpackageview.TravelPackage.CityOrigin.Id).Name;     
                String Destination = _maintenanceCity.Get(travelpackageview.TravelPackage.CityDestination.Id).Name;

                _rdfcontroller.Package(Origin.ToString().Replace("-", "") + "_" +
                Destination.ToString().Replace("-", ""), travelpackageview.TravelPackage.Id);
               
                return RedirectToAction("Index");
            }
            else
            {
                Response.Write("<script>window.location = '" + "Edit/" + Convert.ToString(travelpackageview.TravelPackage.Id + "' </script>"));
                return null;
            }
        }

        [HttpPost]
        public JsonResult Delete(TravelPackage travelpackage, Methods methods)
        {
            this._maintenance.Delete(travelpackage);

            String Origin = methods.GetStringNoAccents(_maintenanceCity.Get(travelpackage.IdCityOrigin).Name);

            String Destination = methods.GetStringNoAccents(_maintenanceCity.Get(travelpackage.IdCityDestination).Name);

            _rdfcontroller.deleteRDF(@"C:\Dell\" + Origin.Replace(" ", "-") + "_to_" +
            Destination.Replace(" ", "-") + ".rdf", Origin, Destination);

            return Json("ok");
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(TravelPackageView travelpackageview)
        {
            if (travelpackageview.TravelPackage.CityOrigin.Id != travelpackageview.TravelPackage.CityDestination.Id)
            {
                this._maintenance.Save(travelpackageview.TravelPackage);

                String Origin = _maintenanceCity.Get(travelpackageview.TravelPackage.CityOrigin.Id).Name;
                String Destination = _maintenanceCity.Get(travelpackageview.TravelPackage.CityDestination.Id).Name;

                _rdfcontroller.Package(Origin.ToString().Replace("-", "") + "_" +
                    Destination.ToString().Replace("-", ""), travelpackageview.TravelPackage.Id);

                return RedirectToAction("Index");
            }
            else
            {
                Response.Write("<script>window.location = '" + "New/" + "' </script>");
                return null;
            }
        }

        public ActionResult Details(TravelPackage travelpackage)
        {
            travelpackage = _maintenance.Get(travelpackage.Id);
            return View(travelpackage);
        }

        public static string Prefixes()
        {
            return "PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>" + System.Environment.NewLine
            + "PREFIX dbpprop: <http://dbpedia.org/property/>" + System.Environment.NewLine;
        }

        public ActionResult SearchCitySparql(int Id, TravelPackageView travelpackageview)
        {
            string Command =

                 @"SELECT ?x ?desc WHERE { ?x a dbpedia-owl:Place; dbpprop:name ?name; dbpedia-owl:abstract " +
                 "?desc. FILTER(str(?name) = " + "'" + _maintenanceCity.Get(Id).Name + "'"
                 + " ) FILTER(langMatches(lang(?desc), 'pt')) }";

            Object results = _maintenancerdf.Get(Prefixes() + Command);

            if (results is SparqlResultSet)
            {
                SparqlResultSet rset = (SparqlResultSet)results;
                string varDesc;

                if (rset.Count >= 1)
                {
                    string str = rset.Results[0].ToString();

                    string[] strs = str.Remove(0, 5).Split('?');

                    varDesc = strs[1].Remove(0, 7);
                }
                else
                    varDesc = "";

                return Json(varDesc, JsonRequestBehavior.AllowGet);
            }
            else
            {
                throw new Exception("query failed " + Command);
            }
        }
    }
}

TravelNM/Views/TravelPackage/BuyPackageIndex.cshtml
@model List<Model.TravelPackage>

@{
    ViewBag.Title = Resources.TravelPackageBuy.Title;
    Layout = "~/Views/Shared/_LayoutAdminCustomer.cshtml";
}

@section css
{
    <link href="~/assets/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet" />
}
    
<div id="page-wrapper">

    <div class="row">
        <!--  page header -->
        <div class="col-lg-12">
            <h1 class="page-header">@Resources.TravelPackageBuy.Title</h1>
        </div>
        <!-- end  page header -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>@Resources.TravelPackageBuy.Instruction</h3> 
                </div>
                <div class="panel-body">
                    <div class="table-responsive table-striped">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>@Resources.TravelPackage.CityOrigin</th>
                                    <th>@Resources.TravelPackage.CityDestination</th>
                                    <th>@Resources.TravelPackage.Priece</th>
                                    <th>-</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (Model.TravelPackage travel in Model)
                                {
                                    <tr>
                                        <td>@travel.Id</td>
                                        <td>@string.Concat(@travel.CityOrigin.Name + "/ " + @travel.CityOrigin.State)</td>
                                        <td>@string.Concat(@travel.CityDestination.Name + "/ " + @travel.CityDestination.State)</td>
                                        <td>@travel.Priece</td>
                                        <td class="center">
                                            <a data-ajax="true" data-ajax-method="POST" data-ajax-success="onSuccessBuy"
                                               href="@Url.Action("CreateCustomer", "TravelPackageBuy", new { id = travel.Id})"
                                               data-ajax-confirm="@string.Concat(@Resources.Global.ConfirmBuyPackage, " ", @travel.CityOrigin.Name, " X ", @travel.CityDestination.Name,
                                               " - $ ", @travel.Priece)"><i class="fa fa-shopping-cart fa-fw"></i></a>

                                            <a href="@Url.Action("Details", "TravelPackage", new { id = travel.Id })"><i class="fa fa-search fa-fw"></i></a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
            <!--End Advanced Tables -->
        </div>
    </div>



</div>


@section scripts {
    <!-- Page-Level Plugin Scripts-->
    <script src="~/assets/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="~/assets/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTables-example').dataTable({
                "language": {
                    "url": "@Resources.Global.DATA_TABLE_JSON"
                }
            });
        });

        function onSuccessBuy(result) {
            if(result == "ok")
            {
                //alert('@Resources.Global.SuccessBuyPackage')
                window.location = '@Url.Action("MyPackage", "TravelPackageBuy")';
            }else
            {
                alert('@Resources.Global.FailedBuyPackage')
            }

            //window.location.reload();
        }

    </script>
}

TravelNM/Views/TravelPackage/Details.cshtml
@model Model.TravelPackage

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdminCustomer.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <!-- page header -->
        <div class="col-lg-12">
            <h1 class="page-header">@Resources.TravelPackageBuy.PackageDetails</h1>
        </div>
        <!--end page header -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <!-- Form Elements -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    @Resources.TravelPackageBuy.MessageConfirm
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="panel-body">
                                <div>
                                    <h4>
                                        <b>@Resources.TravelPackageBuy.CityOrigin:</b> 
                                        @Html.DisplayFor(model => model.CityOrigin.Name) / @Html.DisplayFor(model => model.CityOrigin.State)
                                    </h4>
                                </div>

                                <div>
                                    <h4>
                                        <b>@Resources.TravelPackageBuy.CityDestination:</b>
                                        @Html.DisplayFor(model => model.CityDestination.Name) /
                                        @Html.DisplayFor(model => model.CityDestination.State)
                                    </h4>
                                </div>

                                <div>
                                    <h4>
                                        <b>@Resources.TravelPackageBuy.Priece:</b>
                                        @Html.DisplayFor(model => model.Priece)
                                    </h4>
                                </div>
                                <br />
                                <div>
                                    <h4>
                                        <b>@Resources.TravelPackageBuy.Description:</b>
                                        @Html.DisplayFor(model => model.Description)
                                    </h4>
                                </div>

                                <div class="col-lg-offset-12">
                                    <a data-ajax="true" data-ajax-method="POST" data-ajax-success="onSuccessBuy"
                                       href="@Url.Action("CreateCustomer", "TravelPackageBuy", new { id = Model.Id})">
                                        <i class="btn btn-primary">@Resources.TravelPackageBuy.Buy</i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Form Elements -->
            </div>
        </div>
    </div>
</div>

@section scripts {
    <!-- Page-Level Plugin Scripts-->
    <script src="~/assets/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="~/assets/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTables-example').dataTable({
                "language": {
                    "url": "@Resources.Global.DATA_TABLE_JSON"
                }
            });
        });

        function onSuccessBuy(result) {
            if(result == "ok")
            {
                //alert('@Resources.Global.SuccessBuyPackage')
                window.location = '@Url.Action("MyPackage", "TravelPackageBuy")';
            }else
            {
                alert('@Resources.Global.FailedBuyPackage')
            }

           // window.location.reload();
        }

    </script>
}

TravelNM/Views/TravelPackage/Edit.cshtml
@model TravelNM.Models.TravelPackageView

@{
    ViewBag.Title = Resources.TravelPackage.Edit;
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section css
{
}

<div id="page-wrapper">
    <div class="row">
        <!-- page header -->
        <div class="col-lg-12">
            <h1 class="page-header">@Resources.TravelPackage.Edit</h1>
        </div>
        <!--end page header -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <!-- Form Elements -->
            <div class="panel panel-default">
                <div class="panel-heading">
                   @Resources.TravelPackage.EnterYourInformationBelow
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                        @using (Html.BeginForm("Update", "TravelPackage", FormMethod.Post, new { @id = "form_travelpackage" }))
                        {
                            @Html.HiddenFor(model => Model.TravelPackage.Id)

                            @Html.Partial("_Form", Model);
                            <button type="submit" class="btn btn-primary">@Resources.Global.Update</button>
                        }
                        </div>                    
                    </div>
                </div>
            </div>
            <!-- End Form Elements -->
        </div>
    </div>
</div>

@section scripts {
    <script src="~/Scripts/jquery.maskedinput.min.js"></script>
    <script src="~/Scripts/jquery-maskmoney.js"></script>
    <script>
        jQuery(function ($) {
            $("#TravelPackage_Priece").maskMoney({ showSymbol: false, symbol: "R$", decimal: ".", thousands: "" });
        });
    </script>


    <script>
        function SearchCitySparql() {
            var cityId = $('#TravelPackage_CityDestination_Id').val()
        $.ajax({
            url: '@Url.Action("SearchCitySparql", "TravelPackage")',
            type: "GET",
            dataType: "JSON",
            data: { Id: cityId },
            success: function (varDesc) {
                $("#TravelPackage_Description").html(""); 
                $("#TravelPackage_Description").html(varDesc);
            }
        });
      }
    </script>

}

TravelNM/Views/TravelPackage/Index.cshtml
@model List<Model.TravelPackage>

@{
    ViewBag.Title = Resources.TravelPackage.Title;
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section css
{
    <link href="~/assets/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet" />
}

<div id="page-wrapper">

    <div class="row">
        <!--  page header -->
        <div class="col-lg-12">
            <h1 class="page-header">@Resources.TravelPackage.Title</h1>
        </div>
        <!-- end  page header -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="@Url.Action("New", "TravelPackage")" class="btn btn-info" aria-label="Left Align">
                        @Resources.TravelPackage.New
                    </a>
                </div>
                <div class="panel-body">
                    <div class="table-responsive table-striped">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>@Resources.TravelPackage.CityOrigin</th>
                                    <th>@Resources.TravelPackage.CityDestination</th>
                                    <th>@Resources.TravelPackage.Priece</th>
                                    <th>-</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (Model.TravelPackage travel in Model)
                                {
                                    <tr>
                                        <td>@travel.Id</td>
                                        <td>@string.Concat(@travel.CityOrigin.Name + "/ " + @travel.CityOrigin.State)</td>
                                        <td>@string.Concat(@travel.CityDestination.Name + "/ " + @travel.CityDestination.State)</td>
                                        <td>@travel.Priece</td>
                                        <td class="center">
                                            <a href="@Url.Action("Edit", "TravelPackage", new { id = travel.Id })"><i class="fa fa-edit fa-fw"></i></a>
                                            <a data-ajax="true" data-ajax-method="POST" data-ajax-success="onSuccessDelete" 
                                            href="@Url.Action("Delete", "TravelPackage", new { id = travel.Id,
                                                 IdCityOrigin = travel.CityOrigin.Id, 
                                                 IdCityDestination = travel.CityDestination.Id })" 
                                            data-ajax-confirm="@Resources.Global.ConfirmRemove"><i class="fa fa-trash-o fa-fw"></i></a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
            <!--End Advanced Tables -->
        </div>
    </div>



</div>


@section scripts {
    <!-- Page-Level Plugin Scripts-->
    <script src="~/assets/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="~/assets/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTables-example').dataTable({
                "language": {
                    "url": "@Resources.Global.DATA_TABLE_JSON"
                }
            });
        });

        function onSuccessDelete(result) {
            if(result == "ok")
            {
                alert('@Resources.Global.SuccessRemove')
            }else
            {
                alert('@Resources.Global.FailRemove')
            }

            window.location.reload();
        }

    </script>
}

TravelNM/Views/TravelPackage/New.cshtml
@model TravelNM.Models.TravelPackageView

@{
    ViewBag.Title = Resources.TravelPackage.New;
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@section css
{
}

<div id="page-wrapper">
    <div class="row">
        <!-- page header -->
        <div class="col-lg-12">
            <h1 class="page-header">@Resources.TravelPackage.New</h1>
        </div>
        <!--end page header -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <!-- Form Elements -->
            <div class="panel panel-default">
                <div class="panel-heading">
                   @Resources.TravelPackage.EnterYourInformationBelow
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                        @using (Html.BeginForm("Create", "TravelPackage", FormMethod.Post, new { @id = "form_travelpackage" }))
                            {
                                @Html.Partial("_Form", Model.TravelPackage);                         
                                <button type="submit" class="btn btn-primary">@Resources.Global.Create</button>
                            }
                        </div>
                       
                    </div>
                </div>
            </div>
            <!-- End Form Elements -->
        </div>
    </div>
</div>


@section scripts {
    <script src="~/Scripts/jquery.maskedinput.min.js"></script>
    <script src="~/Scripts/jquery-maskmoney.js"></script>
    <script>
        jQuery(function ($) {
            $("#TravelPackage_Priece").maskMoney({ showSymbol: false, symbol: "R$", decimal: ".", thousands: "" });
        });
    </script>

    <script>
        function SearchCitySparql() {
            var cityId = $('#TravelPackage_CityDestination_Id').val()
            $.ajax({
            url:'@Url.Action("SearchCitySparql", "TravelPackage")',
            type: "GET",
            dataType: "JSON",
            data: { Id: cityId },
            success: function (varDesc) {
                $("#TravelPackage_Description").html(""); 
                $("#TravelPackage_Description").html(varDesc);
            }
        });
      }
    </script>
}

TravelNM/Views/TravelPackage/_Form.cshtml
@model TravelNM.Models.TravelPackageView

@Html.AntiForgeryToken()
@Html.ValidationSummary(true)

<div class="form-group">
    <font id="msgSameCities" color="red">@Resources.TravelPackage.SameCities</font>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.TravelPackage.CityOrigin.Id, Resources.TravelPackage.CityOrigin)
    @Html.DropDownListFor(model => model.TravelPackage.CityOrigin.Id, new SelectList((from c in Model.Cities.ToList()
                                                                                       select new
                                                                                       {
                                                                                           Value = c.Id,
                                                                                           Text = c.Name + "/ " + c.State
                                                                                       }), "Value", "Text"),
    new { @class = "form-control", @required = true })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.TravelPackage.CityDestination.Id, Resources.TravelPackage.CityDestination)
    @Html.DropDownListFor(model => model.TravelPackage.CityDestination.Id, new SelectList((from c in Model.Cities.ToList()
                                                                                            select new
                                                                                            {
                                                                                                Value = c.Id,
                                                                                                Text = c.Name + "/ " + c.State
                                                                                            }), "Value", "Text"),
new
{
    @class = "form-control",
    @required = true,
    @onchange = "SearchCitySparql()"
})
</div>
<div class="form-group">
    @Html.LabelFor(model => model.TravelPackage.Priece, Resources.TravelPackage.Priece)
    @Html.TextBoxFor(model => model.TravelPackage.Priece, new { @class = "form-control", @required = true })
</div>

<div class="form-group">
    @Html.LabelFor(model => model.TravelPackage.Description, Resources.TravelPackage.Description)
    @Html.TextAreaFor(model => model.TravelPackage.Description, new { @class = "form-control", @required = true, cols = 25, @rows = 5 })
</div>